const cover=document.getElementById('coverScreen'),videoScreen=document.getElementById('videoScreen'),video=document.getElementById('openingVideo'),invitation=document.getElementById('invitation'),musicButton=document.getElementById('musicToggle'),music=document.getElementById('cardMusic');
let opened=false,musicOn=false;
async function startMusic(){music.volume=.45;try{await music.play();musicOn=true;musicButton.hidden=false;musicButton.classList.add('playing');musicButton.classList.remove('muted');musicButton.setAttribute('aria-label','إيقاف الموسيقى')}catch{musicOn=false}}
function stopMusic(){music.pause();musicOn=false;musicButton.classList.remove('playing');musicButton.classList.add('muted');musicButton.setAttribute('aria-label','تشغيل الموسيقى')}
function showInvitation(){if(!invitation.hidden)return;videoScreen.classList.add('is-leaving');setTimeout(()=>{videoScreen.hidden=true;invitation.hidden=false;window.scrollTo(0,0)},430)}
async function openCard(){if(opened)return;opened=true;startMusic();videoScreen.hidden=false;requestAnimationFrame(()=>videoScreen.classList.add('visible'));cover.classList.add('is-leaving');setTimeout(()=>cover.hidden=true,450);try{video.currentTime=0;await video.play()}catch{showInvitation()}}
document.getElementById('openInvitation').addEventListener('click',openCard);document.getElementById('skipVideo').addEventListener('click',showInvitation);video.addEventListener('ended',showInvitation);musicButton.addEventListener('click',()=>musicOn?stopMusic():startMusic());
document.querySelectorAll('.link-hotspot').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const url=button.dataset.link;if(url)window.location.assign(url)}));
const weddingDate=new Date('2026-09-19T19:00:00+03:00');function updateCountdown(){let diff=Math.max(0,weddingDate-Date.now());const values=[Math.floor(diff/86400000),Math.floor(diff%86400000/3600000),Math.floor(diff%3600000/60000),Math.floor(diff%60000/1000)];['days','hours','minutes','seconds'].forEach((id,i)=>document.getElementById(id).textContent=String(values[i]).padStart(2,'0'))}updateCountdown();setInterval(updateCountdown,1000);
