const cover=document.getElementById('coverScreen'),videoScreen=document.getElementById('videoScreen'),video=document.getElementById('openingVideo'),invitation=document.getElementById('invitation'),musicButton=document.getElementById('musicToggle');
let opened=false,audioContext,masterGain,phraseTimer,musicOn=false;
function tone(freq,start,duration,volume=.025){const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.setValueAtTime(freq,start);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.07);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);osc.connect(gain).connect(masterGain);osc.start(start);osc.stop(start+duration+.05)}
function musicalPhrase(){if(!musicOn||!audioContext)return;const now=audioContext.currentTime+.05;[[261.63,329.63,392],[220,261.63,329.63],[174.61,220,261.63],[196,246.94,293.66]].forEach((chord,i)=>{chord.forEach((f,j)=>tone(f,now+i*2.4,3.5,j===0?.016:.011));[chord[0]*2,chord[1]*2,chord[2]*2,chord[1]*2].forEach((f,j)=>tone(f,now+i*2.4+j*.55,1.25,.018))})}
function startMusic(){if(!audioContext){audioContext=new(window.AudioContext||window.webkitAudioContext)();masterGain=audioContext.createGain();masterGain.gain.value=.85;masterGain.connect(audioContext.destination)}audioContext.resume();masterGain.gain.cancelScheduledValues(audioContext.currentTime);masterGain.gain.setTargetAtTime(.85,audioContext.currentTime,.08);musicOn=true;musicalPhrase();clearInterval(phraseTimer);phraseTimer=setInterval(musicalPhrase,9600);musicButton.hidden=false;musicButton.classList.add('playing');musicButton.classList.remove('muted');musicButton.setAttribute('aria-label','إيقاف الموسيقى')}
function stopMusic(){musicOn=false;clearInterval(phraseTimer);if(masterGain)masterGain.gain.setTargetAtTime(.0001,audioContext.currentTime,.15);musicButton.classList.remove('playing');musicButton.classList.add('muted');musicButton.setAttribute('aria-label','تشغيل الموسيقى')}
function showInvitation(){if(!invitation.hidden)return;videoScreen.classList.add('is-leaving');setTimeout(()=>{videoScreen.hidden=true;invitation.hidden=false;window.scrollTo(0,0)},430)}
async function openCard(){if(opened)return;opened=true;startMusic();videoScreen.hidden=false;requestAnimationFrame(()=>videoScreen.classList.add('visible'));cover.classList.add('is-leaving');setTimeout(()=>cover.hidden=true,450);try{video.currentTime=0;await video.play()}catch{showInvitation()}}
document.getElementById('openInvitation').addEventListener('click',openCard);document.getElementById('skipVideo').addEventListener('click',showInvitation);video.addEventListener('ended',showInvitation);musicButton.addEventListener('click',()=>musicOn?stopMusic():startMusic());
document.querySelectorAll('.link-hotspot').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const url=button.dataset.link;if(url)window.location.assign(url)}));
const weddingDate=new Date('2026-09-19T19:00:00+03:00');function updateCountdown(){let diff=Math.max(0,weddingDate-Date.now());const values=[Math.floor(diff/86400000),Math.floor(diff%86400000/3600000),Math.floor(diff%3600000/60000),Math.floor(diff%60000/1000)];['days','hours','minutes','seconds'].forEach((id,i)=>document.getElementById(id).textContent=String(values[i]).padStart(2,'0'))}updateCountdown();setInterval(updateCountdown,1000);document.addEventListener('visibilitychange',()=>{if(document.hidden&&audioContext)audioContext.suspend();else if(musicOn&&audioContext)audioContext.resume()});
